services:
  db:
    image: postgres:16
    container_name: expense_tracker_dev_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - expense_tracker_dev_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  expense_tracker_dev_db_data: