openapi: 3.0.0
info:
  title: Expense Tracker API
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000
    description: development server
security:
  - BearerAuth: []
paths:
  /auth:
    $ref: users/paths/auth.yml
  /users:
    $ref: users/paths/users.yml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
