openapi: 3.0.0
info:
  title: Expense Tracker API
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000
    description: development server
security:
  - BearerAuth: []
paths:
  /auth:
    post:
      security: []
      operationId: authenticateUser
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          description: Invalid e-mail or password.
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /users:
    post:
      security: []
      operationId: createUser
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserBody'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /expenses:
    post:
      operationId: createExpense
      summary: Create a new expense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExpenseBody'
      responses:
        '201':
          description: Expense created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          description: Authentication required.
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    get:
      operationId: getExpenses
      summary: Retrieve expenses
      description: Retrieve expenses based on query parameters for reference date and period.
      parameters:
        - name: ref
          in: query
          description: The reference date to start the period from.
          required: true
          schema:
            type: string
            format: date
            example: '2024-07-23'
        - name: period
          in: query
          description: The period to retrieve expenses for.
          required: true
          schema:
            type: string
            enum:
              - 15d
              - 30d
              - 45d
              - 90d
              - 1m
              - 2m
              - 3m
            example: 45d
      responses:
        '200':
          description: Successfully retrieved expenses.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expense'
              examples:
                expenses:
                  summary: Example response with expenses
                  value:
                    - id: uuid
                      amount: '45.50'
                      date: '2024-07-02T00:00:00.000Z'
                      description: Expensive dinner
                    - id: uuid
                      amount: '150.00'
                      date: '2024-07-01T00:00:00.000Z'
                      description: Office supplies
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          description: Authentication required.
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /expenses/{id}:
    put:
      operationId: updateExpense
      summary: Updates an existing expense
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExpenseBody'
      responses:
        '200':
          description: Expense updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateExpenseBody'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          description: Authentication required.
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
    delete:
      operationId: deleteExpense
      summary: Deletes an existing expense
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Expense removed successfully
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          description: Authentication required.
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthBody:
      properties:
        email:
          type: string
          example: example@email.com
        password:
          type: string
          minLength: 8
      required:
        - email
        - password
    Token:
      properties:
        token:
          type: string
          description: JSON Web Token
      required:
        - token
    Message:
      properties:
        message:
          type: string
      required:
        - message
    CreateUserBody:
      properties:
        email:
          type: string
          example: example@email.com
        password:
          type: string
          minLength: 8
        passwordConfirmation:
          type: string
          minLength: 8
      required:
        - email
        - password
        - passwordConfirmation
    Expense:
      properties:
        id:
          type: string
          example: uuid
        description:
          type: string
          example: Groceries
        amount:
          type: string
          example: '100.50'
        date:
          type: string
          format: date
          example: '2024-07-22'
      required:
        - id
        - description
        - amount
        - date
    CreateExpenseBody:
      properties:
        description:
          type: string
          example: Groceries
        amount:
          type: string
          example: '100.50'
        date:
          type: string
          format: date
          example: '2024-07-22'
      required:
        - description
        - amount
        - date
    UpdateExpenseBody:
      properties:
        description:
          type: string
          example: Groceries
        amount:
          type: string
          example: '100.50'
        date:
          type: string
          format: date
          example: '2024-07-22'
  responses:
    BadRequestResponse:
      description: Bad request (Invalid input parameters)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
    InternalServerErrorResponse:
      description: Internal server error
  parameters:
    id:
      name: id
      in: path
      schema:
        type: string
      required: true
